"""empty message

Revision ID: 27048e6a03c0
Revises: 
Create Date: 2020-04-22 18:36:11.538759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27048e6a03c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=23), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_user')
    # ### end Alembic commands ###
