"""empty message

Revision ID: 526d8e77cc41
Revises: 7046c3e54d66
Create Date: 2020-08-29 13:15:28.937548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526d8e77cc41'
down_revision = '7046c3e54d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('citycode', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('my_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=23), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('one',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('two', sa.String(length=100), nullable=True),
    sa.Column('three', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('three'),
    sa.UniqueConstraint('two')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('one')
    op.drop_table('my_user')
    op.drop_table('city')
    # ### end Alembic commands ###
