"""city code added

Revision ID: 7046c3e54d66
Revises: b219d8034162
Create Date: 2020-05-04 20:51:56.060253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7046c3e54d66'
down_revision = 'b219d8034162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('citycode', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'citycode')
    # ### end Alembic commands ###
