"""empty message

Revision ID: bb96b2342957
Revises: 57cf0d7736a9
Create Date: 2020-04-22 19:27:15.680645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb96b2342957'
down_revision = '57cf0d7736a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('two', sa.String(length=100), nullable=True),
    sa.Column('three', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('three'),
    sa.UniqueConstraint('two')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('one')
    # ### end Alembic commands ###
