"""empty message

Revision ID: e1d5c2850ccf
Revises: bb96b2342957
Create Date: 2020-04-22 19:32:24.089384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d5c2850ccf'
down_revision = 'bb96b2342957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('country', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'country')
    # ### end Alembic commands ###
